export const idiomas = {
    ES: {
        onboarding: { btn1: "Siguiente", btn2: "Ya tengo cuenta.", btn3: "Comenzar"},
        iniciosession: { titulo: "Iniciá sesión", leyenda: "Completá tus datos para ingresar a tu cuenta", 
        mail: "Ingresá tu mail",mail_ph: "jose@gmail.com", clave: "Ingresá tu contraseña", datos:"Recordar mis datos", btn1:"Iniciar sesión", 
        btn2:"Olvidé mi contraseña", btn3:"Ingresar sin registrarme", errorMail: {err1:"Mail incorrecto", err2:"wer"}, 
        errorClave: {err1:"Tu contraseña debe tener 4 caraceres", err2:"wer"}},
        recuperaclave: { titulo: "Recuperá tu contraseña", leyenda: "Completá tus datos para recuperar tu contraseña", 
        mail: "Ingresá tu mail",mail_ph: "jose@gmail.com", documento: "Ingresá el DNI del titular",documento_ph: "99999999", btn1:"Recuperar contraseña", 
        errorMail: {err1:"Mail incorrecto", err2:"wer"}, 
        errorDocumento: {err1:"Documento incorrecto", err2:"wer"}},
        recuperaclavemsg: { titulo: "¡Todo listo para recuperar tu contraseña!", leyenda: "Ingresá a tu casilla de mail y seguí los pasos para recuperar tu contraseña."},
        crearclave: { titulo: "Creá tu contraseña", leyenda: "Creá tu nueva contraseña para volver a acceder a tu cuenta.", 
        clave1: "Ingresá tu nueva contraseña", clave2: "Repetí tu nueva contraseña", btn1:"Crear nueva contraseña", 
        errorClave1: {err1:"Clave1 incorrecto", err2:"wer"}, 
        errorClave2: {err1:"Clave2 incorrecto", err2:"wer"}}, 
        crearclavemsg: { titulo: "¡Genial!", leyenda: "Tu contraseña fue creada con éxito.", btn1:"Ingresar a mi cuenta"},
        accesoplan: { titulo: "Accedé a tu Plan Iké", leyenda: "Ingresá el DNI del titular para acceder a tu cobertura.", 
        documento:"Ingresá el DNI del titular",documento_ph:"99999999", btn1:"Ingresar a mi cobertura", 
        btn2:"Quiero contratar un Plan Iké", btn3:"Ingresar sin registrarme", btn4:"Ya tengo cuenta",  btn5:"Ayuda", 
        errorDocumento: {err1:"Documento incorrecto", err2:"wer"}},
        vercobertura: { titulo: "¿Necesitás ayuda con tu cobertura Iké Mascotas?", leyenda: "Contacta a un asesor para hacer consultas o contratar un plan.", 
        btn1:"Ver planes disponibles", btn2:"Contactar a un asesor de Iké", btn3:"Volver"},
        usuarioregistro: { titulo: "Creá tu cuenta", leyenda: "Ahora completá tus datos para crear tu cuenta.", 
        lblNombre:"Tu nombre", lblNombre_ph:"Jose Perez", lblMail:"Tu mail", lblMail_ph:"Jose@gmail.com", lblCelu:"Tu celular", lblCelu_ph:"1142334586", 
        lblClave1:"Creá tu contraseña", lblClave2:"Repeti tu contraseña",
        btn1:"Crear cuenta", btn2:"¿Qué incluye mi cobertura?", btn3:"Ingresar sin registrarme"},
        plandetalle: { titulo: "Plan Mascotas 110", leyenda: "Este plan incluye las siguientes prestaciones:", 
        btn1:"Descargar póliza", btn2:"Ver todos los planes"},
        principal: { tituloCabecera: "Hola, Lucía", leyendaCabecera: "Bienvenida a Iké, tu asistencia de mascotas.", lblConsulta: "Tenés una consulta en 10 minutos", btnConsulta: "Ingresar", lblFlier: "Visitá al veterinario, sin moverte del sillón.",
        btnFlier:"Ingresar", carro1: [{lbl:"Club Iké"},{lbl:"Ecommerce"},{lbl:"Agendar Alarma"}],
        carro2: [{lbl:""},{lbl:""},{lbl:""}],lblNovedades:"Novedades Iké",
        lblAyuda:"¿Necesitás ayuda?. Estamos para lo que necesites.",btnAyuda:"Solicitar asistencia"},
        pie: { inicio: "Inicio", mascota: "Mascotas", consulta: "Consultas", vacuna: "Vacunas", foto: "Fotos"},
        usuariodetalle: {titulo:"Tu perfil", leyenda:"Bienvenida a tu cuenta, encontrarás tu info personal y detalle de plan."},
        mascota:{titulo:"Mis mascotas",leyenda:"Creá el perfil de tus mascotas y accedé a su historia clínica.",label:"Mis mascotas",btn:"Agregar mascota",raza:"Raza: ", edad:"Edad: ", consultas:" Consulta/s"},
        misconsultas:{titulo:"Mis consultas",leyenda:"Creá el perfil de tus mascotas y accedé a su historia clínica.",label:"Mis consultas",btn:"Agendar consulta",verDetalle:"Ver detalle: "},
        calendario:{titulo:"Calendario de Vacunas",leyenda:"Consultá el calendario y registrá las vacunas de tus mascotas.",btn:"Registrar vacuna",perro:"Perros",gato:"Gatos",verDetalle:"Ver detalle: "},
        fotogaleria:{titulo:"Mis fotos",leyenda:"Creá tu galería de fotos en Iké."},
        video: {conectando: "Conectando ..."},
        videocalificacion: {titulo: "Calificá la consulta",leyenda:"Calificando tus consultas nos ayudás a mejorar el servicio para vos y los que más querés!",
        calificaLbl: "¿Cómo calificarías la atención que acabas de recibir?",comentarioLbl:"Dejanos un comentario (opcional)",
        btn1:"Guardar calificación",btn2:"Ahora no"}
    }
}

